# Generated by Django 2.0.4 on 2018-04-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('img', models.ImageField(upload_to='core/products')),
            ],
        ),
    ]
